### PR TITLE
Bug 1204521 - Add a Node.js static webserver & Heroku configuration

### PR DESCRIPTION
**Pull request by edmorley**
See individual commit diffs/messages for more details.

This has been deployed to https://mozilla-bugherder.herokuapp.com/ already. After this lands, we'll need to enable auto-deploy from master and then set up the custom domain/coordinate with IT to hook up https://bugherder.mozilla.org

@KWierso, I'll also get you added to the Heroku account etc - just give me your preferred email address for the invite link.

### CODE REVIEW

**Comment by KWierso** [comment]
Lets use wkocher @ moco

**Comment by edmorley** [comment]
Added :-)
Please also enabled 2FA on the account.

**Comment by KWierso** [comment]
Done.

**Comment by edmorley** [comment]
> Done.

2FA is still showing as not enabled for your account?

**Pull request merged**
