### PR TITLE
Bug 1161171 - Stop stripping the cset URL parameter when showing error pages

### PR DESCRIPTION
**Pull request by KWierso**

### CODE REVIEW

**Comment by edmorley** [comment]
I think it would be better to modify the go() function to just not throw away the cset and repo, which would avoid having to add boilerplate everywhere. It seems like that may even be as simple as modifying this line:
https://github.com/mozilla/bugherder/blob/e968f7d9e0f63af0541338e21d265e078653c676/js/bugherder.js#L533

**Comment by graememcc** [comment]
Drive-by comments.

Think I agree with Ed here. I had a vague feeling that there was a specific reason I didn't persist these originally, but of course it's too much to ask that I might have documented why.

I suspect it might have been related to possible ambiguity in handling errors once Bugherder started handling multiple trees: if loading the pushlog failed, was it because the user specified right cset/wrong tree or wrong cset/right tree? However, it's probably not worth worrying about that scenario too much: most invocations these days will presumably be incoming traffic from Treeherder with the correct query string and no manual input. (We could probably file a new bug to add a `<select>` to the input form to specify the tree if necessary.)

The forEach over the persisted array below the linked line not only constructs strings for the fragment of query string to be persisted, but also normalizes them, turning things like debug=foo into debug=1. The logic would need to be changed here to not mutate the changeset/tree.

I think we'd also need to add logic for prioritizing parameters from the query string supplied in the go method's query parameter. (If there's a cset in the query parameter, it came from user input, so should take precedence over any saved state).

**Comment by KWierso** [comment]
How about this?

As a side note, it seems like the items in 'persisted' only actually persist when their values are already '1'. (eg, "debug=foo" was removed, even without my patch, but "debug=1" is persisted)

**Comment by edmorley** [comment]
I'd prefer to defer to Graham on this, I'm not sure I really follow the current PR (it seems a bit hacky?).
Feel free to land as-is if you'd prefer though - I don't really have much of a stake in bugherder any more :-)

**Comment by edmorley** [comment]
> As a side note, it seems like the items in 'persisted' only actually persist when their values are already '1'. (eg, "debug=foo" was removed, even without my patch, but "debug=1" is persisted)

Yeah this is what Graeme mentioned in https://github.com/mozilla/bugherder/pull/23#issuecomment-128082930

**Pull request merged**
